// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modul4HW6.DataAccess;

namespace Modul4HW6.DataAccess.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211127123113_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Modul4HW6.DataAccess.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Inst");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NumberOfPhone");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2015, 7, 20, 18, 30, 25, 0, DateTimeKind.Unspecified),
                            Email = "Email1@gmail.com",
                            InstagramUrl = "https://inst1.com",
                            Name = "Artist1",
                            Phone = "+123456789"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1980, 6, 20, 18, 30, 25, 0, DateTimeKind.Unspecified),
                            Email = "Email1@gmail.com",
                            InstagramUrl = "https://inst2.com",
                            Name = "Artist2",
                            Phone = "+789456123"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1990, 5, 20, 18, 30, 25, 0, DateTimeKind.Unspecified),
                            Email = "Email1@gmail.com",
                            InstagramUrl = "https://inst3.com",
                            Name = "Artist3",
                            Phone = "+456123789"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2000, 4, 20, 18, 30, 25, 0, DateTimeKind.Unspecified),
                            Email = "Email1@gmail.com",
                            InstagramUrl = "https://inst4.com",
                            Name = "Artist4",
                            Phone = "+123789456"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2010, 3, 20, 18, 30, 25, 0, DateTimeKind.Unspecified),
                            Email = "Email5@gmail.com",
                            InstagramUrl = "https://inst5.com",
                            Name = "Artist5",
                            Phone = "+654987321"
                        });
                });

            modelBuilder.Entity("Modul4HW6.DataAccess.Models.ArtistSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("SongId");

                    b.ToTable("ArtistSongs");
                });

            modelBuilder.Entity("Modul4HW6.DataAccess.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Title1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Title2"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Title3"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Title4"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Title5"
                        });
                });

            modelBuilder.Entity("Modul4HW6.DataAccess.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Duration")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Duration");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleasedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReleaseDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 2.5m,
                            GenreId = 0,
                            ReleasedDate = new DateTime(2015, 7, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Butter"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 2.3m,
                            GenreId = 0,
                            ReleasedDate = new DateTime(1976, 7, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Leave the door open"
                        },
                        new
                        {
                            Id = 3,
                            Duration = 2.0m,
                            GenreId = 0,
                            ReleasedDate = new DateTime(2001, 7, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kiss me more"
                        },
                        new
                        {
                            Id = 4,
                            Duration = 1.5m,
                            GenreId = 0,
                            ReleasedDate = new DateTime(2014, 7, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Save your tears"
                        },
                        new
                        {
                            Id = 5,
                            Duration = 1.8m,
                            GenreId = 0,
                            ReleasedDate = new DateTime(2020, 7, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "good 4 u"
                        });
                });

            modelBuilder.Entity("Modul4HW6.DataAccess.Models.ArtistSong", b =>
                {
                    b.HasOne("Modul4HW6.DataAccess.Models.Artist", "Artist")
                        .WithMany("ArtistSong")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modul4HW6.DataAccess.Models.Song", "Song")
                        .WithMany("ArtistSong")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Modul4HW6.DataAccess.Models.Song", b =>
                {
                    b.HasOne("Modul4HW6.DataAccess.Models.Genre", "Genre")
                        .WithMany("Songs")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Modul4HW6.DataAccess.Models.Artist", b =>
                {
                    b.Navigation("ArtistSong");
                });

            modelBuilder.Entity("Modul4HW6.DataAccess.Models.Genre", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Modul4HW6.DataAccess.Models.Song", b =>
                {
                    b.Navigation("ArtistSong");
                });
#pragma warning restore 612, 618
        }
    }
}
